### ISSUE TITLE
from where can i access kitti.names?

### ISSUE THREAD

**Issue by sparshgarg23** [chidianlizi/yolov4_kitti#1]
you have mentioned kitti.names,please let me know from where can I access the file

**Comment by chidianlizi** [comment]
hi, this file is a text file to store the type of object. you can find the file i used under the folder _training_, compared to the official version i omitted the dontcare and misc classes.

**Comment by sparshgarg23** [comment]
thanks is it okay if I reach out to you in case of any issues

**Comment by chidianlizi** [comment]
sure

**Comment by sparshgarg23** [comment]
Currently training the model,and I observed that the confidence loss is very high in the range of 300.
I have set batch size to 8 which results in the no of steps to be 32750.
As such at step 1655 confidence loss is 375.96,prob loss is 25,and total loss is apprx 400
Is this okay,at what point did you observe the confidence loss decreasing

**Comment by sparshgarg23** [comment]
was able to visualize the training curves,things look fine,at some point loss ends up decreasing in a consistent manner.Thanks

**Comment by sparshgarg23** [comment]
Is it okay with you,if i add this work on my resume as well as my personal repo?

**Comment by chidianlizi** [comment]
no problem, glad it was helpful to you.
